name: face_skin_detection_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  google_ml_kit: ^0.19.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  bloc: ^8.1.4
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banner.png
    - assets/icons/
    - assets/data/intents.json
